# Generated by Django 4.2.30 on 2026-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_verified_alter_user_pin_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
