# Generated by Django 4.2.30 on 2026-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_activationtoken_method_user_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
