# Generated by Django 4.2.30 on 2026-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_service_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'TÃ©lÃ©phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'TÃ©lÃ©phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
