# Generated by Django 4.2.30 on 2026-06-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, default='', max_length=20)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Heartbeat',
                'verbose_name_plural': 'Device Heartbeats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='heartbeat_interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['fingerprint'], name='monitoring__fingerp_9d79e0_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_active'], name='monitoring__user_id_cc90da_idx'),
        ),
        migrations.AddIndex(
            model_name='forwardedsms',
            index=models.Index(fields=['target_device', 'received_at'], name='monitoring__target__408e4c_idx'),
        ),
        migrations.AddField(
            model_name='deviceheartbeat',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='monitoring.device'),
        ),
    ]
