# Generated by Django 4.2.30 on 2026-06-26 10:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('operator', models.CharField(db_index=True, max_length=20)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('airtime_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('data_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('data_unit', models.CharField(default='MB', max_length=10)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SIM Balance',
                'verbose_name_plural': 'SIM Balances',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('adjustment', 'Adjustment')], max_length=20)),
                ('category', models.CharField(choices=[('mm_deposit', 'Mobile Money Deposit'), ('mm_withdrawal', 'Mobile Money Withdrawal'), ('mm_transfer', 'Mobile Money Transfer'), ('airtime_sale', 'Airtime Sale'), ('data_sale', 'Data Bundle Sale'), ('bill_payment', 'Bill Payment'), ('commission', 'Commission'), ('fee', 'Fee'), ('subscription', 'Subscription Payment'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='CDF', max_length=10)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sim_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='ledger.simbalance')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ledger_ledg_user_id_a6cf64_idx'), models.Index(fields=['sim_balance', 'created_at'], name='ledger_ledg_sim_bal_874a99_idx')],
            },
        ),
    ]
