# Generated by Django 4.2.30 on 2026-06-11 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('AIRTEL', 'Airtel'), ('ORANGE', 'Orange'), ('VODACOM', 'Vodacom'), ('AFRICELL', 'Africell')], max_length=20)),
                ('type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('AIRTIME', 'Airtime'), ('BUNDLE', 'Bundle'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='CDF', max_length=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_sms', models.TextField()),
                ('transaction_date', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='FailedParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sms', models.TextField()),
                ('operator', models.CharField(choices=[('AIRTEL', 'Airtel'), ('ORANGE', 'Orange'), ('VODACOM', 'Vodacom'), ('AFRICELL', 'Africell')], max_length=20)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_parses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
